### ISSUE TITLE
No plugin icon and setting menu

### ISSUE THREAD

**Issue by howarddo2208** [hkgnp/logseq-todoist-plugin#53]
![image](https://user-images.githubusercontent.com/62332195/212138689-5eebc6b3-5dfe-4731-a3c0-4573827ef1c2.png)
![image](https://user-images.githubusercontent.com/62332195/212138799-ad226a9e-5134-43c7-8da0-20a6b4b0d8c6.png)
![image](https://user-images.githubusercontent.com/62332195/212139048-76808fb8-489d-46d0-9926-111277bd9627.png)

Logseq version: 0.8.16
Plugin version: 5.2.0

**Comment by hkgnp** [comment]
Should be fixed in 5.2.1. Please try.

**Comment by howarddo2208** [comment]
> Should be fixed in 5.2.1. Please try.

The setting menu is back but still no icon in the plugin dropdown tho.

**Comment by howarddo2208** [comment]
Oh, I didn't know that, just started using this plugin and the documentation said there is

**Comment by hkgnp** [comment]
> Oh, I didn't know that, just started using this plugin and the documentation said there is

Yeah apologies. The READMEs for all my plugins are significantly outdated. 😢

**Comment by howarddo2208** [comment]
just forked the project, may I ask why the methods are imported from non exist folder? I changed to services/todoistHelpers but removePrefix is still missing. How can you build that without error? I'm brand new to plugin dev, so it would be great help if you can explain it. Also, are there any resources you recommend for logseq development?
![image](https://user-images.githubusercontent.com/62332195/212229835-c8d0bab0-02f1-4add-8b1d-0752f403a1fb.png)

**Comment by howarddo2208** [comment]
The unpacked version pull from the master branch still faced the same problem.

**Comment by howarddo2208** [comment]
nvm, it was my bad

**Comment by hkgnp** [comment]
Great! Hmm, I am not a software engineer by training so I am not sure if I am the best person to ask 😂

But I use Javscript and Typescript and the plugin API methods can be found at [https://plugins-doc.logseq.com](https://plugins-doc.logseq.com). It is perhaps best to start with a particular idea you have in mind and learn how to build it by looking at other similar plugins.

Feel free to ask any questions in Discord! I go by the same handle.
